### ISSUE TITLE
jdbc导入数据报错

### ISSUE THREAD

**Issue by muyannian** [lucene-cn/lxdb#120]
Sat Feb 20 10:57:21 CST 2021 WARN: Invalid value 'null' for server variable named 'max_allowed_packet', falling back to sane default of '-1'.
Sat Feb 20 10:57:21 CST 2021 WARN: Invalid value 'null' for server variable named 'net_buffer_length', falling back to sane default of '16,384'.
INSERT INTO stu (primarykey, id, name, score, consume, weight) VALUES ('cfcd208495d565ef66e7dff9f98764da_0', 1, 'zhangsan', 94.5, 3000.23, 80)
INSERT INTO stu (primarykey, id, name, score, consume, weight) VALUES ('cfcd208495d565ef66e7dff9f98764da_0', 1, 'zhangsan', 94.5, 3000.23, 80)
Exception in thread "main" java.sql.SQLException: Could not retrieve transaction read-only status from server
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:878)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:874)
	at com.mysql.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:3523)
	at com.mysql.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:3490)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:759)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:729)
	at com.lx.hive.Mysql.main(Mysql.java:29)
Caused by: java.sql.SQLException: Invalid value for getInt() - 'OFF'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2504)
	at com.mysql.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:3519)
	... 4 more

**Comment by muyannian** [comment]
package com.lx.hive;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.*;

public class Mysql {
	 static final String USER = "root";
	    static final String PASS = "123456";
	    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
	    //&characterEncoding=utf-8
	    static final String DB_URL = "jdbc:mysql://192.168.2.142:5077?useSSL=false&characterEncoding=utf-8";
	    static String sql = "select database()";
	    public static void main(String[] args) throws Exception {
	        Class.forName(JDBC_DRIVER);
	        Connection conn = null;

	        conn = DriverManager.getConnection(DB_URL,USER,PASS);

	        Statement statement = conn.createStatement();
	        for(int i=0;i<1000000;i++)
	        {
	        	String str="INSERT INTO stu (primarykey, id, name, score, consume, weight) VALUES ('"+stringToMD5(String.valueOf(i))+"_"+i+"', 1, 'zhangsan', 94.5, 3000.23, 80)";
	        	System.out.println(str);
	        	if(i%10000==0)
	        	{
	        		System.out.println(str);
	        	}
		        statement.execute(str);

	        }

	        ResultSet use_default = statement.executeQuery("select * from test limit 100");

	        System.out.println("id\tage");

	        while(use_default.next()){
	            System.out.println(use_default.getString(1)+"\t"+use_default.getString(2));
	        }

	        conn.close();
	    }
	    
	    
	    public static String stringToMD5(String plainText) {
	        byte[] secretBytes = null;
	        try {
	            secretBytes = MessageDigest.getInstance("md5").digest(
	                    plainText.getBytes());
	        } catch (NoSuchAlgorithmException e) {
	            throw new RuntimeException("没有这个md5算法！");
	        }
	        String md5code = new BigInteger(1, secretBytes).toString(16);
	        for (int i = 0; i < 32 - md5code.length(); i++) {
	            md5code = "0" + md5code;
	        }
	        return md5code;
	    }
}

**Comment by muyannian** [comment]
如果是导入数据需要使用 executeUpdate

jdbc导入文档  说明记得调整  @hgs19921112

**Comment by hgs19921112** [comment]
已添加插入数据的例子
