### ISSUE TITLE
分裂后在查询卡主

### ISSUE THREAD

**Issue by muyannian** [lucene-cn/lxdb#22]
分裂后在查询卡主

**Comment by muyannian** [comment]
0: jdbc:hive2://localhost:10000/default> select * from  student5 where name='lisi' limit 10;

执行这个查询后就会触发

**Comment by muyannian** [comment]
2020-12-15 18:30:58,136 INFO  [RpcServer.default.FPBQ.Fifo.handler=29,queue=2,port=16025] regionserver.HydrogenStore: --yanniandebug333_createScanner--
java.io.IOException: ddd
	at org.apache.hadoop.hbase.regionserver.HydrogenStore.createScanner(HydrogenStore.java:517)
	at org.apache.hadoop.hbase.regionserver.HydrogenStore.getScanner(HydrogenStore.java:472)
	at org.apache.hadoop.hbase.regionserver.HRegion$RegionScannerImpl.initializeScanners(HRegion.java:6487)
	at org.apache.hadoop.hbase.regionserver.HRegion$RegionScannerImpl.<init>(HRegion.java:6467)
	at org.apache.hadoop.hbase.regionserver.HydrogenRegion.instantiateRegionScanner(HydrogenRegion.java:299)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2979)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2961)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2955)
	at org.apache.hadoop.hbase.regionserver.HydrogenRegion.getScanner(HydrogenRegion.java:270)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.newRegionScanner(RSRpcServices.java:3071)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.scan(RSRpcServices.java:3385)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:42278)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:418)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:338)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:318)
2020-12-15 18:30:58,174 INFO  [hconnection-0x3f3c7bdb-shared-pool5-t1] client.ScannerCallable: Open scanner=6946774903068557313 for scan={"filter":"GlobalFilter{queryFilter\u003dSingleColumnValueFilter (f, name, EQUAL, lisi), aggregationFilter\u003dnull, keyOnly\u003dfalse, groupColumn\u003d[], limit\u003d10}","startRow":"","stopRow":"5","batch":-1,"cacheBlocks":true,"totalColumns":4,"maxResultSize":"2097152","families":{"f":["id","name","primarykey","score"]},"caching":2000,"maxVersions":1,"timeRange":["0","9223372036854775807"]} on region region=student5,,1608025781203.0ee98b523616bf4ad2950e6f3e66d666., hostname=test3,16025,1608028218338, seqNum=1356
2020-12-15 18:30:58,260 INFO  [Executor task launch worker for task 0] executor.Executor: Finished task 0.0 in stage 0.0 (TID 0). 1148 bytes result sent to driver
2020-12-15 18:30:58,329 INFO  [dispatcher-event-loop-1] executor.HydrogenExecutor: Got assigned task 1
2020-12-15 18:30:58,329 INFO  [Executor task launch worker for task 1] executor.Executor: Running task 0.0 in stage 1.0 (TID 1)

**Comment by muyannian** [comment]
java.lang.ThreadLocal$ThreadLocalMap.getEntryAfterMiss(ThreadLocal.java:444)
java.lang.ThreadLocal$ThreadLocalMap.getEntry(ThreadLocal.java:419)
java.lang.ThreadLocal$ThreadLocalMap.access$000(ThreadLocal.java:298)
java.lang.ThreadLocal.get(ThreadLocal.java:163)
java.lang.StringCoding.deref(StringCoding.java:63)
java.lang.StringCoding.decode(StringCoding.java:179)
java.lang.String.<init>(String.java:426)
org.apache.hadoop.hbase.util.Bytes.toString(Bytes.java:605)
org.apache.hadoop.hbase.util.Bytes.toString(Bytes.java:549)
org.apache.hadoop.hbase.regionserver.HydrogenStoreScanner.seekToNextKey(HydrogenStoreScanner.java:520)
org.apache.hadoop.hbase.regionserver.HydrogenStoreScanner.next(HydrogenStoreScanner.java:602)
org.apache.hadoop.hbase.regionserver.KeyValueHeap.next(KeyValueHeap.java:153)
org.apache.hadoop.hbase.regionserver.HRegion$RegionScannerImpl.populateResult(HRegion.java:6663)
org.apache.hadoop.hbase.regionserver.HRegion$RegionScannerImpl.nextInternal(HRegion.java:6827)
org.apache.hadoop.hbase.regionserver.HRegion$RegionScannerImpl.nextRaw(HRegion.java:6597)
org.apache.hadoop.hbase.regionserver.RSRpcServices.scan(RSRpcServices.java:3224) => holding Monitor(org.apache.hadoop.hbase.regionserver.HRegion$RegionScannerImpl@845040441})
org.apache.hadoop.hbase.regionserver.RSRpcServices.scan(RSRpcServices.java:3469)
org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:42278)
org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:418)
org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:133)
org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:338)
org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:318)

**Comment by muyannian** [comment]
当某种原因导致的           rowkey匹配不到值，会导致进入      this.heap.next();  不断进行死循环

在这里添加计数，如果所有hfile都找不到这个记录，则skip这个rowkey
