### ISSUE TITLE
并行运行分裂有BUG

### ISSUE THREAD

**Issue by muyannian** [lucene-cn/lxdb#26]
:43:51,500 INFO  [regionserver/test2:16026.Chore.1] hbase.ScheduledChore: MovedRegionsCleaner for region test2,16026,1608866388018 average execution time: 4160 ns.
2020-12-25 11:43:54,131 INFO  [RS_OPEN_REGION-regionserver/test2:16026-2] handler.AssignRegionHandler: Open student3,1,1608867785411.58db7c47786a42c834bb906d546311d1.
2020-12-25 11:43:54,132 INFO  [RS_OPEN_REGION-regionserver/test2:16026-2] coprocessor.CoprocessorHost: System coprocessor org.apache.hadoop.hbase.coprocessor.HydrogenRegionComprocessor loaded, priority=536870911.
2020-12-25 11:43:54,211 INFO  [StoreOpener-58db7c47786a42c834bb906d546311d1-1] hfile.CacheConfig: Created cacheConfig: cacheDataOnRead=true, cacheDataOnWrite=false, cacheIndexesOnWrite=false, cacheBloomsOnWrite=false, cacheEvictOnClose=false, cacheDataCompressed=false, prefetchOnOpen=false for family {NAME => 'f', VERSIONS => '1', EVICT_BLOCKS_ON_CLOSE => 'false', NEW_VERSION_BEHAVIOR => 'false', KEEP_DELETED_CELLS => 'FALSE', CACHE_DATA_ON_WRITE => 'false', DATA_BLOCK_ENCODING => 'NONE', TTL => 'FOREVER', MIN_VERSIONS => '0', REPLICATION_SCOPE => '0', BLOOMFILTER => 'ROW', CACHE_INDEX_ON_WRITE => 'false', IN_MEMORY => 'false', CACHE_BLOOMS_ON_WRITE => 'false', PREFETCH_BLOCKS_ON_OPEN => 'false', COMPRESSION => 'NONE', BLOCKCACHE => 'true', BLOCKSIZE => '65536'} with blockCache=LruBlockCache{blockCount=2, currentSize=3.04 MB, freeSize=4.00 GB, maxSize=4 GB, heapSize=3.04 MB, minSize=3.80 GB, minFactor=0.95, multiSize=1.90 GB, multiFactor=0.5, singleSize=972.80 MB, singleFactor=0.25}
2020-12-25 11:43:54,212 INFO  [StoreOpener-58db7c47786a42c834bb906d546311d1-1] compactions.CompactionConfiguration: size [128 MB, 8.00 EB, 8.00 EB); files [3, 10); ratio 1.200000; off-peak ratio 5.000000; throttle point 2684354560; major period 604800000, major jitter 0.500000, min locality to compact 0.000000; tiered compaction: max_age 9223372036854775807, incoming window min 6, compaction policy for tiered window org.apache.hadoop.hbase.regionserver.compactions.ExploringCompactionPolicy, single output for minor true, compaction window factory org.apache.hadoop.hbase.regionserver.compactions.ExponentialCompactionWindowFactory
2020-12-25 11:43:54,225 INFO  [StoreOpener-58db7c47786a42c834bb906d546311d1-1] regionserver.HStore: Store=f,  memstore type=DefaultMemStore, storagePolicy=HOT, verifyBulkLoads=false, parallelPutCountPrintThreshold=50, encoding=NONE, compression=NONE
2020-12-25 11:43:54,314 INFO  [StoreOpener-58db7c47786a42c834bb906d546311d1-1] cl.2578: localOrLink_hdfs://test1:9000/Hydrogen/raw_split_default/link/100157/20201225114305_student3_470e7a359011d335c81bb9d5714f7ab1_segments_4.raw
2020-12-25 11:43:54,317 INFO  [StoreOpener-58db7c47786a42c834bb906d546311d1-1] cl.2578: localOrLink_hdfs://test1:9000/Hydrogen/raw_split_default/link/100157/20201225114305_student3_470e7a359011d335c81bb9d5714f7ab1_segments_4.raw
2020-12-25 11:43:54,319 INFO  [StoreOpener-58db7c47786a42c834bb906d546311d1-1] cl.2578: localOrLink_hdfs://test1:9000/Hydrogen/raw_split_default/link/100157/20201225114305_student3_470e7a359011d335c81bb9d5714f7ab1_segments_4.raw
2020-12-25 11:43:54,320 ERROR [StoreOpener-58db7c47786a42c834bb906d546311d1-1] directory.HdfsDirectory$HdfsIndexInput: length
java.io.FileNotFoundException: File does not exist: hdfs://test1:9000/Hydrogen/data/default/student3/58db7c47786a42c834bb906d546311d1/f_index/segments_4
	at org.apache.hadoop.hdfs.DistributedFileSystem$27.doCall(DistributedFileSystem.java:1444)
	at org.apache.hadoop.hdfs.DistributedFileSystem$27.doCall(DistributedFileSystem.java:1437)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1437)
	at com.luxin.hydrogen.directory.HdfsDirectory$HdfsIndexInput$1.call(HdfsDirectory.java:348)
	at com.luxin.hydrogen.directory.HdfsDirectory$HdfsIndexInput$1.call(HdfsDirectory.java:345)
	at com.luxin.hydrogen.directory.hdfslink.FilesRef.localOrLink(FilesRef.java:91)
	at com.luxin.hydrogen.directory.HdfsDirectory$HdfsIndexInput.getlength_nocache(HdfsDirectory.java:345)
	at com.luxin.hydrogen.directory.HdfsDirectory$HdfsIndexInput.length(HdfsDirectory.java:328)
	at com.luxin.hydrogen.directory.CustomBufferedIndexInput.refill(CustomBufferedIndexInput.java:166)
	at com.luxin.hydrogen.directory.CustomBufferedIndexInput.readByte(CustomBufferedIndexInput.java:29)
	at org.apache.lucene.store.BufferedChecksumIndexInput.readByte(BufferedChecksumIndexInput.java:41)
	at org.apache.lucene.store.DataInput.readInt(DataInput.java:102)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:305)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:291)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:899)
	at org.apache.hadoop.hbase.regionserver.HydrogenStoreEngine.newEmptyIndexWriter(HydrogenStoreEngine.java:135)
	at org.apache.hadoop.hbase.regionserver.HydrogenStoreEngine.open(HydrogenStoreEngine.java:621)
	at org.apache.hadoop.hbase.regionserver.HydrogenStore.<init>(HydrogenStore.java:189)
	at org.apache.hadoop.hbase.regionserver.HydrogenRegion.instantiateHStore(HydrogenRegion.java:107)
	at org.apache.hadoop.hbase.regionserver.HRegion$1.call(HRegion.java:1105)
	at org.apache.hadoop.hbase.regionserver.HRegion$1.call(HRegion.java:1102)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-12-25 11:43:54,323 INFO  [StoreOpener-58db7c47786a42c834bb906d546311d1-1] cl.2578: localOrLink_hdfs://test1:9000/Hydrogen/raw_split_default/link/100157/20201225114305_student3_470e7a359011d335c81bb9d5714f7ab1_segments_4.raw
2020-12-25 11:43:54,326 INFO  [StoreOpener-58db7c47786a42c834bb906d546311d1-1] cl.2578: localOrLink_hdfs://test1:9000/Hydrogen/raw_split_default/link/100157/20201225114305_student3_470e7a359011d335c81bb9d5714f7ab1_segments_4.raw
2020-12-25 11:43:54,328 INFO  [StoreOpener-58db7c47786a42c834bb906d546311d1-1] cl.2578: localOrLink_hdfs://test1:9000/Hydrogen/raw_split_default/link/100157/20201225114305_student3_470e7a359011d335c81bb9d5714f7ab1_segments_4.raw
2020-12-25 11:43:54,329 ERROR [StoreOpener-58db7c47786a42c834bb906d546311d1-1] directory.HdfsDirectory$HdfsIndexInput: length
java.io.FileNotFoundException: File does not exist: hdfs://test1:9000/Hydrogen/data/default/student3/58db7c47786a42c834bb906d546311d1/f_index/segments_4
	at org.apache.hadoop.hdfs.DistributedFileSystem$27.doCall(DistributedFileSystem.java:1444)
	at org.apache.hadoop.hdfs.DistributedFileSystem$27.doCall(DistributedFileSystem.java:1437)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1437)
	at com.luxin.hydrogen.directory.HdfsDirectory$HdfsIndexInput$1.call(HdfsDirectory.java:348)
	at com.luxin.hydrogen.directory.HdfsDirectory$HdfsIndexInput$1.call(HdfsDirectory.java:345)
	at com.luxin.hydrogen.directory.hdfslink.FilesRef.localOrLink(FilesRef.java:91)
	at com.luxin.hydrogen.directory.HdfsDirectory$HdfsIndexInput.getlength_nocache(HdfsDirectory.java:345)
	at com.luxin.hydrogen.directory.HdfsDirectory$HdfsIndexInput.length(HdfsDirectory.java:328)
	at com.luxin.hydrogen.directory.CustomBufferedIndexInput.refill(CustomBufferedIndexInput.java:167)
	at com.luxin.hydrogen.directory.CustomBufferedIndexInput.readByte(CustomBufferedIndexInput.java:29)
	at org.apache.lucene.store.BufferedChecksumIndexInput.readByte(BufferedChecksumIndexInput.java:41)
	at org.apache.lucene.store.DataInput.readInt(DataInput.java:102)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:305)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:291)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:899)
	at org.apache.hadoop.hbase.regionserver.HydrogenStoreEngine.newEmptyIndexWriter(HydrogenStoreEngine.java:135)
	at org.apache.hadoop.hbase.regionserver.HydrogenStoreEngine.open(HydrogenStoreEngine.java:621)
	at org.apache.hadoop.hbase.regionserver.HydrogenStore.<init>(HydrogenStore.java:189)
	at org.apache.hadoop.hbase.regionserver.HydrogenRegion.instantiateHStore(HydrogenRegion.java:107)
	at org.apache.hadoop.hbase.regionserver.HRegion$1.call(HRegion.java:1105)
	at org.apache.hadoop.hbase.regionserver.HRegion$1.call(HRegion.java:1102)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-12-25 11:43:54,329 ERROR [RS_OPEN_REGION-regionserver/test2:16026-2] regionserver.HRegion: Could not initialize all stores for the region=student3,1,1608867785411.58db7c47786a42c834bb906d546311d1.
2020-12-25 11:43:54,329 WARN  [RS_OPEN_REGION-regionserver/test2:16026-2] regionserver.HRegion: Failed initialize of region= student3,1,1608867785411.58db7c47786a42c834bb906d546311d1., starting to roll back memstore
java.io.IOException: org.apache.lucene.index.CorruptIndexException: Unexpected file read error while reading index. (resource=BufferedChecksumIndexInput(segments_4))
	at org.apache.hadoop.hbase.regionserver.HRegion.initializeStores(HRegion.java:1141)
	at org.apache.hadoop.hbase.regionserver.HRegion.initializeStores(HRegion.java:1083)
	at org.apache.hadoop.hbase.regionserver.HRegion.initializeRegionInternals(HRegion.java:980)
	at org.apache.hadoop.hbase.regionserver.HRegion.initialize(HRegion.java:932)
	at org.apache.hadoop.hbase.regionserver.HRegion.openHRegion(HRegion.java:7357)
	at org.apache.hadoop.hbase.regionserver.HRegion.openHRegion(HRegion.java:7315)
	at org.apache.hadoop.hbase.regionserver.HRegion.openHRegion(HRegion.java:7287)
	at org.apache.hadoop.hbase.regionserver.HRegion.openHRegion(HRegion.java:7245)
	at org.apache.hadoop.hbase.regionserver.HRegion.openHRegion(HRegion.java:7196)
	at org.apache.hadoop.hbase.regionserver.handler.AssignRegionHandler.process(AssignRegionHandler.java:133)
	at org.apache.hadoop.hbase.executor.EventHandler.run(EventHandler.java:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.lucene.index.CorruptIndexException: Unexpected file read error while reading index. (resource=BufferedChecksumIndexInput(segments_4))
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:293)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:899)
	at org.apache.hadoop.hbase.regionserver.HydrogenStoreEngine.newEmptyIndexWriter(HydrogenStoreEngine.java:135)
	at org.apache.hadoop.hbase.regionserver.HydrogenStoreEngine.open(HydrogenStoreEngine.java:621)
	at org.apache.hadoop.hbase.regionserver.HydrogenStore.<init>(HydrogenStore.java:189)
	at org.apache.hadoop.hbase.regionserver.HydrogenRegion.instantiateHStore(HydrogenRegion.java:107)
	at org.apache.hadoop.hbase.regionserver.HRegion$1.call(HRegion.java:1105)
	at org.apache.hadoop.hbase.regionserver.HRegion$1.call(HRegion.java:1102)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: java.io.EOFException: read past EOF: segments_4
	at com.luxin.hydrogen.directory.CustomBufferedIndexInput.refill(CustomBufferedIndexInput.java:169)
	at com.luxin.hydrogen.directory.CustomBufferedIndexInput.readByte(CustomBufferedIndexInput.java:29)
	at org.apache.lucene.store.BufferedChecksumIndexInput.readByte(BufferedChecksumIndexInput.java:41)
	at org.apache.lucene.store.DataInput.readInt(DataInput.java:102)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:305)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:291)
	... 13 more
2020-12-25 11:43:54,334 WARN  [RS_OPEN_REGION-regionserver/test2:16026-2] handler.AssignRegionHandler: Failed to open region student3,1,1608867785411.58db7c47786a42c834bb906d546311d1., will report to master
java.io.IOException: The new max sequence id 1 is less than the old max sequence id 1129
	at org.apache.hadoop.hbase.wal.WALSplitUtil.writeRegionSequenceIdFile(WALSplitUtil.java:410)
	at org.apache.hadoop.hbase.regionserver.HRegion.writeRegionCloseMarker(HRegion.java:1212)
	at org.apache.hadoop.hbase.regionserver.HRegion.doClose(HRegion.java:1751)
	at org.apache.hadoop.hbase.regionserver.HRegion.close(HRegion.java:1565)
	at org.apache.hadoop.hbase.regionserver.HRegion.close(HRegion.java:1511)
	at org.apache.hadoop.hbase.regionserver.HRegion.openHRegion(HRegion.java:7370)
	at org.apache.hadoop.hbase.regionserver.HRegion.openHRegion(HRegion.java:7315)
	at org.apache.hadoop.hbase.regionserver.HRegion.openHRegion(HRegion.java:7287)
	at org.apache.hadoop.hbase.regionserver.HRegion.openHRegion(HRegion.java:7245)
	at org.apache.hadoop.hbase.regionserver.HRegion.openHRegion(HRegion.java:7196)
	at org.apache.hadoop.hbase.regionserver.handler.AssignRegionHandler.process(AssignRegionHandler.java:133)
	at org.apache.hadoop.hbase.executor.EventHandler.run(EventHandler.java:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-12-25 11:43:55,533 INFO  [RefreshScheduleService-1-thread-1] luxin.HydrogenSlave: RefreshScheduleService-1-thread-1: Ready To Start scheduleTask.
2020-12-25 11:43:55,533 INFO  [RefreshScheduleService-1-thread-1] regionserver.HydrogenStoreEngine: Refresh true timetaken: 0 s.
2020-12-25 11:44:00,533 INFO  [RefreshScheduleService-1-thread-1] luxin.HydrogenSlave: RefreshScheduleService-1-thread-1: Ready To Start scheduleTask.
2020-12-25 11:44:00,533 INFO  [RefreshScheduleService-1-thread-1] regionserver.HydrogenStoreEngine: Refresh true timetaken: 0 s.
2020-12-25 11:44:05,533 INFO  [RefreshScheduleService-1-thread-1] luxin.HydrogenSlave: RefreshScheduleService-1-thread-1: Ready To Start scheduleTask.
2020-12-25 11:44:05,533 INFO  [RefreshScheduleService-1-thread-1] regionserver.HydrogenStoreEngine: Refresh true timetaken: 0 s.
2020-12-25 11:44:10,533 INFO  [RefreshScheduleService-1-thread-1] luxin.HydrogenSlave: RefreshScheduleService-1-thread-1: Ready To Start scheduleTask.
2020-12-25 11:44:10,533 INFO  [RefreshScheduleService-1-thread-1] regionserver.HydrogenStoreEngine: Refresh true timetaken: 0 s.
2020-12-25 11:44:15,532 INFO  [RefreshScheduleService-1-thread-1] luxin.HydrogenSlave: Refresh

**Comment by muyannian** [comment]
修正
