### ISSUE TITLE
索引的分裂与合并

### ISSUE THREAD

**Issue by muyannian** [lucene-cn/lxdb#3]

**Comment by muyannian** [comment]
测试用的建表语句
先测试手工分裂

CREATE TABLE IF NOT EXISTS default.student(
  id int_is
  ,name string_is
  ,score double_is)
 tblproperties("enableSplit"="enabled");


create table hydrogen(id int_id primary key,name string_is,age short_id,weight long_id,score double_id,consume float_id,date string_id,isok boolean_id)tblproperties("enableSplit"="enabled");

**Comment by muyannian** [comment]
导入一些数据
INSERT INTO student(id, name, score) VALUES (4, "lisi", 94.3);

**Comment by muyannian** [comment]
alter table user disabled;

**Comment by muyannian** [comment]
flush table student

**Comment by muyannian** [comment]
java.lang.Long.toString(Long.java:135)
org.apache.lucene.store.RAMDirectory.createTempOutput(RAMDirectory.java:202)
com.luxin.hydrogen.directory.NRTCachingDirectory.createTempOutput(NRTCachingDirectory.java:260)
org.apache.lucene.store.FilterDirectory.createTempOutput(FilterDirectory.java:79)
org.apache.lucene.store.TrackingDirectoryWrapper.createTempOutput(TrackingDirectoryWrapper.java:51)
org.apache.lucene.codecs.lucene80.Lucene80DocValuesConsumer$CompressedBinaryBlockWriter.<init>(Lucene80DocValuesConsumer.java:378)
org.apache.lucene.codecs.lucene80.Lucene80DocValuesConsumer.addBinaryField(Lucene80DocValuesConsumer.java:500)
org.apache.lucene.codecs.perfield.PerFieldDocValuesFormat$FieldsWriter.addBinaryField(PerFieldDocValuesFormat.java:114)
org.apache.lucene.index.BinaryDocValuesWriter.flush(BinaryDocValuesWriter.java:138)
org.apache.lucene.index.DefaultIndexingChain.writeDocValues(DefaultIndexingChain.java:322)
org.apache.lucene.index.DefaultIndexingChain.flush(DefaultIndexingChain.java:201)
org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:379)
org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:480)
org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:660)
org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:564) => holding Monitor(java.lang.Object@312313409})
org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:294)
org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:269)
org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:259)
org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:140)
com.luxin.hydrogen.index.HydrogenReaderManager.refreshIfNeeded(HydrogenReaderManager.java:31)
com.luxin.hydrogen.index.HydrogenReaderManager.refreshIfNeeded(HydrogenReaderManager.java:14)
org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
org.apache.lucene.search.ReferenceManager.maybeRefresh(ReferenceManager.java:225)
org.apache.hadoop.hbase.regionserver.HydrogenStoreEngine.refresh(HydrogenStoreEngine.java:531)
org.apache.hadoop.hbase.regionserver.HydrogenStoreEngine.maybeRefresh(HydrogenStoreEngine.java:417)
org.apache.hadoop.hbase.regionserver.HydrogenStoreEngine.indexDocument(HydrogenStoreEngine.java:282)
org.apache.hadoop.hbase.regionserver.HydrogenStore.add(HydrogenStore.java:281)
org.apache.hadoop.hbase.regionserver.HRegion.applyToMemStore(HRegion.java:4514)
org.apache.hadoop.hbase.regionserver.HRegion.access$500(HRegion.java:229)
org.apache.hadoop.hbase.regionserver.HRegion$BatchOperation.applyFamilyMapToMemStore(HRegion.java:3569)
org.apache.hadoop.hbase.regionserver.HRegion$BatchOperation.lambda$writeMiniBatchOperationsToMemStore$0(HRegion.java:3259)
org.apache.hadoop.hbase.regionserver.HRegion$BatchOperation$$Lambda$541/124976959.visit(Unknown Source)
org.apache.hadoop.hbase.regionserver.HRegion$BatchOperation.visitBatchOperations(HRegion.java:3192)
org.apache.hadoop.hbase.regionserver.HRegion$BatchOperation.writeMiniBatchOperationsToMemStore(HRegion.java:3251)
org.apache.hadoop.hbase.regionserver.HRegion$MutationBatchOperation.writeMiniBatchOperationsToMemStore(HRegion.java:3734)
org.apache.hadoop.hbase.regionserver.HRegion.doMiniBatchMutate(HRegion.java:4152)
org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:4081)
org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:4012)
org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:4003)
org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:4017)
org.apache.hadoop.hbase.regionserver.HRegion.doBatchMutate(HRegion.java:4348)
org.apache.hadoop.hbase.regionserver.HRegion.put(HRegion.java:3135)
org.apache.hadoop.hbase.regionserver.RSRpcServices.mutate(RSRpcServices.java:2910)
org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:42276)
org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:418)
org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:133)
org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:338)
org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:318)

**Comment by muyannian** [comment]
[root@test2 bin]# ./hadoop fs -cat  /Hydrogen/data/default/student4/975f2e0aca4e80f66542b5888da92eee/f_index/segments_2.link
{"root_path_first":"100001","root_path_last":"100001","prefix_first":"20201215165359_f60ad44c-3f5e-4d11-ac02-cdc71de75b96","prefix_last":"20201215165359_f60ad44c-3f5e-4d11-ac02-cdc71de75b96","raw_first":"hdfs://test1:9000/Hydrogen/data/default/student4/95cfb4336affc0bc07960930e2589ee7/f_index","raw_last":"hdfs://test1:9000/Hydrogen/data/default/student4/95cfb4336affc0bc07960930e2589ee7/f_index","daughter_1":"hdfs://test1:9000/Hydrogen/data/default/student4/95cfb4336affc0bc07960930e2589ee7/.splits/975f2e0aca4e80f66542b5888da92eee/f_index","daughter_2":"hdfs://test1:9000/Hydrogen/data/default/student4/95cfb4336affc0bc07960930e2589ee7/.splits/4a3ffbfe18098ac31090785aac287eb5/f_index","uuid1":"128e394d-2e41-49be-9b1d-2a57a2e1db3e","uuid2":"e11b9631-ba48-4179-8768-c08fbbc64b55","yyyyMMddHHmmss":"20201215165359","raw_fileName_first":"segments_2","raw_fileName_last":"segments_2","isLinks":"false","uuid1_base_path":"/data/hardlink/default/link/100001/20201215165359_f60ad44c-3f5e-4d11-ac02-cdc71de75b96_segments_2_128e394d-2e41-49be-9b1d-2a57a2e1db3e.link","uuid2_base_path":"/data/hardlink/default/link/100001/20201215165359_f60ad44c-3f5e-4d11-ac02-cdc71de75b96_segments_2_e11b9631-ba48-4179-8768-c08fbbc64b55.link","uuid1_link_path":"hdfs://test1:9000/Hydrogen/data/default/student4/95cfb4336affc0bc07960930e2589ee7/.splits/975f2e0aca4e80f66542b5888da92eee/f_index/segments_2.link","uuid2_link_path":"hdfs://test1:9000/Hydrogen/data/default/student4/95cfb4336affc0bc07960930e2589ee7/.splits/4a3ffbfe18098ac31090785aac287eb5/f_index/segments_2.link","index_key":"uuid1"}[root@test2 bin]#

**Comment by muyannian** [comment]
package com.lx.hive;

import org.apache.hadoop.yarn.webapp.hamlet.Hamlet;

import java.sql.*;

/**
 * @author: cy
 * @date: 2020-09-17 10:25
 * @descriptions:
 */
public class Hive {

    private static String driverName = "org.apache.hive.jdbc.HiveDriver";

    public static void main(String[] args) throws SQLException {
        try {
            Class.forName(driverName);
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }

        Connection connection = DriverManager.getConnection("jdbc:hive2://192.168.2.142:10000/default;auth=noSasl", "", "");
        Statement statement = connection.createStatement();
        for(int i=0;i<100000;i++)
        {
            statement.execute("INSERT INTO student5(id, name, score) VALUES ("+i+", 'lisi',94.3) ");
            
            

        }
        String sql  = "select * from student where id=5 limit 10";
        ResultSet resultSet = statement.executeQuery(sql);

        while (resultSet.next()) {
            System.out.println(String.valueOf(resultSet.getInt(1)) + "\t" + resultSet.getString(2)+ "\t" + resultSet.getString(3));
        }


    }
}

**Comment by muyannian** [comment]
调试过程中清理zk

/opt/software/zookeeper/bin/zkServer.sh stop
rm -rf /data/zookeeper/data/version-2

/opt/software/zookeeper/bin/zkServer.sh start

**Comment by muyannian** [comment]
2020-12-24 18:22:38,867 INFO  [StoreFileSplitter-%1$d-pool11-t1] cl.2019: addSplitLink:/Hydrogen/data/default/student/1dce2138ef6bc8465a80cabcf4734cd7/f_index/_4.si@_4.si@_4.si
2020-12-24 18:22:38,908 INFO  [StoreFileSplitter-%1$d-pool11-t1] cl.2019: addSplitLink:/Hydrogen/data/default/student/1dce2138ef6bc8465a80cabcf4734cd7/f_index/_4_Lucene80_0.dvd
2020-12-24 18:22:38,908 INFO  [StoreFileSplitter-%1$d-pool11-t1] cl.2019: addSplitLink:/Hydrogen/data/default/student/1dce2138ef6bc8465a80cabcf4734cd7/f_index/_4_Lucene80_0.dvd@_4_Lucene80_0.dvd@_4_Lucene80_0.dvd
2020-12-24 18:22:38,950 INFO  [StoreFileSplitter-%1$d-pool11-t1] cl.2019: addSplitLink:/Hydrogen/data/default/student/1dce2138ef6bc8465a80cabcf4734cd7/f_index/_4_Lucene80_0.dvm
2020-12-24 18:22:38,950 INFO  [StoreFileSplitter-%1$d-pool11-t1] cl.2019: addSplitLink:/Hydrogen/data/default/student/1dce2138ef6bc8465a80cabcf4734cd7/f_index/_4_Lucene80_0.dvm@_4_Lucene80_0.dvm@_4_Lucene80_0.dvm
2020-12-24 18:22:39,012 INFO  [StoreFileSplitter-%1$d-pool11-t1] cl.2019: addSplitLink:/Hydrogen/data/default/student/1dce2138ef6bc8465a80cabcf4734cd7/f_index/_4_Lucene84_0.doc
2020-12-24 18:22:39,012 INFO  [StoreFileSplitter-%1$d-pool11-t1] cl.2019: addSplitLink:/Hydrogen/data/default/student/1dce2138ef6bc8465a80cabcf4734cd7/f_index/_4_Lucene84_0.doc@_4_Lucene84_0.doc@_4_Lucene84_0.doc
2020-12-24 18:22:39,051 INFO  [StoreFileSplitter-%1$d-pool11-t1] cl.2019: addSplitLink:/Hydrogen/data/default/student/1dce2138ef6bc8465a80cabcf4734cd7/f_index/_4_Lucene84_0.tim
2020-12-24 18:22:39,051 INFO  [StoreFileSplitter-%1$d-pool11-t1] cl.2019: addSplitLink:/Hydrogen/data/default/student/1dce2138ef6bc8465a80cabcf4734cd7/f_index/_4_Lucene84_0.tim@_4_Lucene84_0.tim@_4_Lucene84_0.tim
2020-12-24 18:22:39,090 INFO  [StoreFileSplitter-%1$d-pool11-t1] cl.2019: addSplitLink:/Hydrogen/data/default/student/1dce2138ef6bc8465a80cabcf4734cd7/f_index/_4_Lucene84_0.tip
2020-12-24 18:22:39,090 INFO  [StoreFileSplitter-%1$d-pool11-t1] cl.2019: addSplitLink:/Hydrogen/data/default/student/1dce2138ef6bc8465a80cabcf4734cd7/f_index/_4_Lucene84_0.tip@_4_Lucene84_0.tip@_4_Lucene84_0.tip
2020-12-24 18:22:39,146 INFO  [StoreFileSplitter-%1$d-pool11-t1] cl.2019: addSplitLink:/Hydrogen/data/default/student/1dce2138ef6bc8465a80cabcf4734cd7/f_index/_4_Lucene84_0.tmd
2020-12-24 18:22:39,146 INFO  [StoreFileSplitter-%1$d-pool11-t1] cl.2019: addSplitLink:/Hydrogen/data/default/student/1dce2138ef6bc8465a80cabcf4734cd7/f_index/_4_Lucene84_0.tmd@_4_Lucene84_0.tmd@_4_Lucene84_0.tmd
2020-12-24 18:22:39,187 INFO  [StoreFileSplitter-%1$d-pool11-t1] cl.2019: addSplitLink:/Hydrogen/data/default/student/1dce2138ef6bc8465a80cabcf4734cd7/f_index/segments_2
2020-12-24 18:22:39,187 INFO  [StoreFileSplitter-%1$d-pool11-t1] cl.2019: addSplitLink:/Hydrogen/data/default/student/1dce2138ef6bc8465a80cabcf4734cd7/f_index/segments_2@segments_2@segments_2
2020-12-24 18:22:39,251 INFO  [StoreFileSplitter-%1$d-pool11-t1] assignment.IndexTableRegionProcedure: parentIndex: hdfs://test1:9000/Hydrogen/data/default/student/1dce2138ef6bc8465a80cabcf4734cd7/f_index
2020-12-24 18:22:39,252 INFO  [StoreFileSplitter-%1$d-pool11-t1] assignment.IndexTableRegionProcedure: daughter_1_Index: hdfs://test1:9000/Hydrogen/data/default/student/1dce2138ef6bc8465a80cabcf4734cd7/.splits/3fa724fbf997b7b8cf77a3d2278ae9c9/f_index
2020-12-24 18:22:39,252 INFO  [StoreFileSplitter-%1$d-pool11-t1] assignment.IndexTableRegionProcedure: daughter_2_Index: hdfs://test1:9000/Hydrogen/data/default/student/1dce2138ef6bc8465a80cabcf4734cd7/.splits/ede9ab167032aecef4ca3fa4af130498/f_index
2020-12-24 18:22:39,270 ERROR [PEWorker-3] assignment.IndexTableRegionProcedure: Splitting 1dce2138ef6bc8465a80cabcf4734cd7, pid=12, state=RUNNABLE:SPLIT_TABLE_REGION_CREATE_DAUGHTER_REGIONS, locked=true; IndexTableRegionProcedure table=student, parent=1dce2138ef6bc8465a80cabcf4734cd7, daughterA=3fa724fbf997b7b8cf77a3d2278ae9c9, daughterB=ede9ab167032aecef4ca3fa4af130498
java.io.IOException: Failing split. Expected reference file count isn't equal.
        at org.apache.hadoop.hbase.master.assignment.IndexTableRegionProcedure.assertReferenceFileCount(IndexTableRegionProcedure.java:696)
        at org.apache.hadoop.hbase.master.assignment.IndexTableRegionProcedure.createDaughterRegions(IndexTableRegionProcedure.java:559)
        at org.apache.hadoop.hbase.master.assignment.IndexTableRegionProcedure.executeFromState(IndexTableRegionProcedure.java:232)
        at org.apache.hadoop.hbase.master.assignment.IndexTableRegionProcedure.executeFromState(IndexTableRegionProcedure.java:40)
        at org.apache.hadoop.hbase.procedure2.StateMachineProcedure.execute(StateMachineProcedure.java:194)
        at org.apache.hadoop.hbase.procedure2.Procedure.doExecute(Procedure.java:962)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execProcedure(ProcedureExecutor.java:1662)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.executeProcedure(ProcedureExecutor.java:1409)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.access$1100(ProcedureExecutor.java:78)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor$WorkerThread.run(ProcedureExecutor.java:1979)
2020-12-24 18:22:39,294 INFO  [PEWorker-5] procedure.MasterProcedureScheduler: Waiting on xlock for pid=15, state=RUNNABLE:REGION_STATE_TRANSITION_GET_ASSIGN_CANDIDATE; TransitRegionStateProcedure table=student, region=1dce2138ef6bc8465a80cabcf4734cd7, ASSIGN held by pid=12
2020-12-24 18:22:39,299 INFO  [PEWorker-3] procedure2.ProcedureExecutor: Rolled back pid=12, state=ROLLEDBACK, exception=java.io.IOException via master-split-regions:java.io.IOException: Failing split. Expected reference file count isn't equal.; IndexTableRegionProcedure table=student, parent=1dce2138ef6bc8465a80cabcf4734cd7, daughterA=3fa724fbf997b7b8cf77a3d2278ae9c9, daughterB=ede9ab167032aecef4ca3fa4af130498 exec-time=4.3010sec
2020-12-24 18:22:39,299 INFO  [PEWorker-6] procedure.MasterProcedureScheduler: Took xlock for pid=15, state=RUNNABLE:REGION_STATE_TRANSITION_GET_ASSIGN_CANDIDATE; TransitRegionStateProcedure table=student, region=1dce2138ef6bc8465a80cabcf4734cd7, ASSIGN
2020-12-24 18:22:39,301 INFO  [PEWorker-6] assignment.TransitRegionStateProcedure: Starting pid=15, state=RUNNABLE:REGION_STATE_TRANSITION_GET_ASSIGN_CANDIDATE, locked=true; TransitRegionStateProcedure table=student, region=1dce2138ef6bc8465a80cabcf4734cd7, ASSIGN; rit=CLOSED, location=test2,16022,160

**Comment by muyannian** [comment]
分裂 OK
分裂后的delete
分裂后再分裂
分裂后垃圾的清理
分裂后超过一定时间强制物化

**Comment by muyannian** [comment]
分裂 OK
分裂后的delete ok
分裂后再分裂 ok
分裂后垃圾的清理 ok
分裂后超过一定时间强制物化 暂不实现
