### ISSUE TITLE
进一步测试下数据规模较大的情况下分裂的性能

### ISSUE THREAD

**Issue by muyannian** [lucene-cn/lxdb#33]
进一步测试下数据规模较大的情况下分裂的性能

**Comment by muyannian** [comment]
17fd03a00c581f950f86762855, ASSIGN; rit=OPENING, location=test3,16021,1609150711949
2020-12-28 18:49:28,725 WARN  [PEWorker-15] assignment.TransitRegionStateProcedure: Failed transition, suspend 128secs pid=179, ppid=175, state=RUNNABLE:REGION_STATE_TRANSITION_GET_ASSIGN_CANDIDATE, locked=true; TransitRegionStateProcedure table=student5, region=274cc817fd03a00c581f950f86762855, ASSIGN; rit=OPENING, location=null; waiting on rectified condition fixed by other Procedure or operator intervention
org.apache.hadoop.hbase.HBaseIOException: Failed to open region
        at org.apache.hadoop.hbase.master.assignment.TransitRegionStateProcedure.confirmOpened(TransitRegionStateProcedure.java:256)
        at org.apache.hadoop.hbase.master.assignment.TransitRegionStateProcedure.executeFromState(TransitRegionStateProcedure.java:346)
        at org.apache.hadoop.hbase.master.assignment.TransitRegionStateProcedure.executeFromState(TransitRegionStateProcedure.java:102)
        at org.apache.hadoop.hbase.procedure2.StateMachineProcedure.execute(StateMachineProcedure.java:194)
        at org.apache.hadoop.hbase.master.assignment.TransitRegionStateProcedure.execute(TransitRegionStateProcedure.java:323)
        at org.apache.hadoop.hbase.master.assignment.TransitRegionStateProcedure.execute(TransitRegionStateProcedure.java:102)
        at org.apache.hadoop.hbase.procedure2.Procedure.doExecute(Procedure.java:962)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execProcedure(ProcedureExecutor.java:1662)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.executeProcedure(ProcedureExecutor.java:1409)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.access$1100(ProcedureExecutor.java:78)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor$WorkerThread.run(ProcedureExecutor.java:1979)
2020-12-28 18:49:28,725 INFO  [PEWorker-15] procedure2.TimeoutExecutorThread: ADDED pid=179, ppid=175, state=WAITING_TIMEOUT:REGION_STATE_TRANSITION_GET_ASSIGN_CANDIDATE, locked=true; TransitRegionStateProcedure table=student5, region=274cc817fd03a00c581f950f86762855, ASSIGN; timeout=128000, timestamp=1609152696725
2020-12-28 18:49:28,825 INFO  [PEWorker-5] procedure2.ProcedureExecutor: Finished subprocedure pid=201, resume processing parent pid=178, ppid=175, state=RUNNABLE:REGION_STATE_TRANSITION_CONFIRM_OPENED, locked=true; TransitRegionStateProcedure table=student5, region=4103bfc4550ac0d5e19514f668c9e557, ASSIGN
2020-12-28 18:49:28,826 INFO  [PEWorker-5] procedure2.ProcedureExecutor: Finished pid=201, ppid=178, state=SUCCESS; org.apache.hadoop.hbase.master.assignment.OpenRegionProcedure in 427msec
2020-12-28 18:49:28,826 INFO  [PEWorker-12] assignment.TransitRegionStateProcedure: Retry=11 of max=2147483647; pid=178, ppid=175, state=RUNNABLE:REGION_STATE_TRANSITION_CONFIRM_OPENED, locked=true; TransitRegionStateProcedure table=student5, region=4103bfc4550ac0d5e19514f668c9e557, ASSIGN; rit=OPENING, location=test2,16022,1609150711688
2020-12-28 18:49:28,826 WARN  [PEWorker-12] assignment.TransitRegionStateProcedure: Failed transition, suspend 128secs pid=178, ppid=175, state=RUNNABLE:REGION_STATE_TRANSITION_GET_ASSIGN_CANDIDATE, locked=true; TransitRegionStateProcedure table=student5, region=4103bfc4550ac0d5e19514f668c9e557, ASSIGN; rit=OPENING, location=null; waiting on rectified condition fixed by other Procedure or operator intervention
org.apache.hadoop.hbase.HBaseIOException: Failed to open region
        at org.apache.hadoop.hbase.master.assignment.TransitRegionStateProcedure.confirmOpened(TransitRegionStateProcedure.java:256)
        at org.apache.hadoop.hbase.master.assignment.TransitRegionStateProcedure.executeFromState(TransitRegionStateProcedure.java:346)
        at org.apache.hadoop.hbase.master.assignment.TransitRegionStateProcedure.executeFromState(TransitRegionStateProcedure.java:102)
        at org.apache.hadoop.hbase.procedure2.StateMachineProcedure.execute(StateMachineProcedure.java:194)
        at org.apache.hadoop.hbase.master.assignment.TransitRegionStateProcedure.execute(TransitRegionStateProcedure.java:323)
        at org.apache.hadoop.hbase.master.assignment.TransitRegionStateProcedure.execute(TransitRegionStateProcedure.java:102)
        at org.apache.hadoop.hbase.procedure2.Procedure.doExecute(Procedure.java:962)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execProcedure(ProcedureExecutor.java:1662)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.executeProcedure(ProcedureExecutor.java:1409)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.access$1100(ProcedureExecutor.java:78)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor$WorkerThread.run(ProcedureExecutor.java:1979)
2020-12-28 18:49:28,826 INFO  [PEWorker-12] procedure2.TimeoutExecutorThread: ADDED pid=178, ppid=175, state=WAITING_TIMEOUT:REGION_STATE_TRANSITION_GET_ASSIGN_CANDIDATE, locked=true; TransitRegionStateProcedure table=student5, region=4103bfc4550ac0d5e19514f668c9e557, ASSIGN; timeout=128000, timestamp=1609152696826

**Comment by muyannian** [comment]
还真有问题，上面的报错信息

**Comment by muyannian** [comment]
/Hydrogen_myn/raw_split_default/link/100877下的文件结构

Permission | Owner | Group | Size | Last Modified | Replication | Block Size | Name |  
-- | -- | -- | -- | -- | -- | -- | -- | --
-rw-r--r-- | root | supergroup | 1.33 KB | Dec 28 18:47 | 2 | 128 MB | 20201228184657_student5_d1fa8689659417094ef19f8fe219f29d_segments_8_274cc817fd03a00c581f950f86762855.link |  
-rw-r--r-- | root | supergroup | 1.33 KB | Dec 28 18:47 | 2 | 128 MB | 20201228184657_student5_d1fa8689659417094ef19f8fe219f29d_segments_8_4103bfc4550ac0d5e19514f668c9e557.link |  
-rwxr-xr-x | root | supergroup | 1.52 KB | Dec 28 18:46 | 2 | 128 MB | 20201228184657_student5_d1fa8689659417094ef19f8fe219f29d_segments_8.raw

**Comment by muyannian** [comment]
日志的指向记录
2020-12-28 18:47:11,365 INFO  [StoreFileSplitter-%1$d-pool9-t3] cl.2019: addSplitLink:/Hydrogen_myn/data/default/student5/d1fa8689659417094ef19f8fe219f29d/f_index/segments_8@segments_8@segments_8@{"root_path_first":"100877","root_path_last":"100877","prefix_first":"20201228184657_student5_d1fa8689659417094ef19f8fe219f29d","prefix_last":"20201228184657_student5_d1fa8689659417094ef19f8fe219f29d","raw_first":"/Hydrogen_myn/data/default/student5/d1fa8689659417094ef19f8fe219f29d/f_index","raw_last":"/Hydrogen_myn/data/default/student5/d1fa8689659417094ef19f8fe219f29d/f_index","daughter_1":"/Hydrogen_myn/data/default/student5/4103bfc4550ac0d5e19514f668c9e557/f_index","daughter_2":"/Hydrogen_myn/data/default/student5/274cc817fd03a00c581f950f86762855/f_index","uuid1":"4103bfc4550ac0d5e19514f668c9e557","uuid2":"274cc817fd03a00c581f950f86762855","yyyyMMddHHmmss":"20201228184657","raw_fileName_first":"segments_8","raw_fileName_last":"segments_8","isLinks":"false","uuid1_base_path":"/Hydrogen_myn/raw_split_default/link/100877/20201228184657_student5_d1fa8689659417094ef19f8fe219f29d_segments_8_4103bfc4550ac0d5e19514f668c9e557.link","uuid2_base_path":"/Hydrogen_myn/raw_split_default/link/100877/20201228184657_student5_d1fa8689659417094ef19f8fe219f29d_segments_8_274cc817fd03a00c581f950f86762855.link","uuid1_link_path":"/Hydrogen_myn/data/default/student5/4103bfc4550ac0d5e19514f668c9e557/f_index/segments_8.link","uuid2_link_path":"/Hydrogen_myn/data/default/student5/274cc817fd03a00c581f950f86762855/f_index/segments_8.link"}

**Comment by muyannian** [comment]
链接文件里记录的内容
{"root_path_first":"100879","root_path_last":"100879","prefix_first":"20201228184657_student5_d1fa8689659417094ef19f8fe219f29d","prefix_last":"20201228184657_student5_d1fa8689659417094ef19f8fe219f29d","raw_first":"/Hydrogen_myn/data/default/student5/d1fa8689659417094ef19f8fe219f29d/f_index","raw_last":"/Hydrogen_myn/data/default/student5/d1fa8689659417094ef19f8fe219f29d/f_index","daughter_1":"/Hydrogen_myn/data/default/student5/4103bfc4550ac0d5e19514f668c9e557/f_index","daughter_2":"/Hydrogen_myn/data/default/student5/274cc817fd03a00c581f950f86762855/f_index","uuid1":"4103bfc4550ac0d5e19514f668c9e557","uuid2":"274cc817fd03a00c581f950f86762855","yyyyMMddHHmmss":"20201228184657","raw_fileName_first":"segments_8","raw_fileName_last":"segments_8","isLinks":"false","uuid1_base_path":"/Hydrogen_myn/raw_split_default/link/100879/20201228184657_student5_d1fa8689659417094ef19f8fe219f29d_segments_8_4103bfc4550ac0d5e19514f668c9e557.link","uuid2_base_path":"/Hydrogen_myn/raw_split_default/link/100879/20201228184657_student5_d1fa8689659417094ef19f8fe219f29d_segments_8_274cc817fd03a00c581f950f86762855.link","uuid1_link_path":"/Hydrogen_myn/data/default/student5/4103bfc4550ac0d5e19514f668c9e557/f_index/segments_8.link","uuid2_link_path":"/Hydrogen_myn/data/default/student5/274cc817fd03a00c581f950f86762855/f_index/segments_8.link","index_key":"uuid1"}
