### ISSUE TITLE
blockCache会导致checkSum报错,要弄清楚原因

### ISSUE THREAD

**Issue by muyannian** [lucene-cn/lxdb#55]
我实际测试了下,单独的下载下来文件在本地测试那个文件是没问题的.

报错如下
      "ServerReadQueryPerSecond_5min_rate": 0.057994813933494274,
      "ServerReadQueryPerSecond_15min_rate": 0.023283957991169352,
      "ServerWriteQueryPerSecond_count": 634508,
      "ServerWriteQueryPerSecond_mean_rate": 3164.3802176106446,
      "ServerWriteQueryPerSecond_1min_rate": 8187.985060313492,
      "ServerWriteQueryPerSecond_5min_rate": 1911.557616006629,
      "ServerWriteQueryPerSecond_15min_rate": 657.8142923430977
    }
  ]
}
[2021-01-21 13:13:31.394] (org.apache.hadoop.hbase.regionserver.HRegionServer:2220)[INFO] - ***** STOPPING region server 'test2,16021,1611205808185' *****
[2021-01-21 13:13:31.394] (org.apache.hadoop.hbase.regionserver.HRegionServer:2234)[INFO] - STOPPED: Replay of WAL required. Forcing server shutdown
[2021-01-21 13:13:31.395] (org.apache.hadoop.hbase.regionserver.HRegionServer:159)[ERROR] - ***** ABORTING region server test2,16021,1611205808185: Replay of WAL required. Forcing server shutdown *****
org.apache.hadoop.hbase.DroppedSnapshotException: region: hydrogen_primary,,1611121174391.12f9311d151481db627cdd8cfdff4d02.
        at org.apache.hadoop.hbase.regionserver.HRegion.internalFlushCacheAndCommit(HRegion.java:2876)
        at org.apache.hadoop.hbase.regionserver.HRegion.internalFlushcache(HRegion.java:2545)
        at org.apache.hadoop.hbase.regionserver.HRegion.internalFlushcache(HRegion.java:2517)
        at org.apache.hadoop.hbase.regionserver.HRegion.flushcache(HRegion.java:2407)
        at org.apache.hadoop.hbase.regionserver.MemStoreFlusher.flushRegion(MemStoreFlusher.java:611)
        at org.apache.hadoop.hbase.regionserver.MemStoreFlusher.flushRegion(MemStoreFlusher.java:580)
        at org.apache.hadoop.hbase.regionserver.MemStoreFlusher.access$1000(MemStoreFlusher.java:68)
        at org.apache.hadoop.hbase.regionserver.MemStoreFlusher$FlushHandler.run(MemStoreFlusher.java:360)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
        at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:759)
        at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:774)
        at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:3573)
        at org.apache.hadoop.hbase.regionserver.HydrogenStoreEngine.flushIndex(HydrogenStoreEngine.java:502)
        at org.apache.hadoop.hbase.regionserver.HydrogenStoreFlusher.flushSnapshot(HydrogenStoreFlusher.java:75)
        at org.apache.hadoop.hbase.regionserver.HStore.flushCache(HStore.java:1045)
        at org.apache.hadoop.hbase.regionserver.HydrogenStore.flushCache(HydrogenStore.java:438)
        at org.apache.hadoop.hbase.regionserver.HStore$StoreFlusherImpl.flushCache(HStore.java:2344)
        at org.apache.hadoop.hbase.regionserver.HRegion.internalFlushCacheAndCommit(HRegion.java:2812)
        ... 8 more
Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=0 actual=17b83ffc (resource=BufferedChecksumIndexInput(_fr7_Lucene84_0.tim))
        at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:419)
        at org.apache.lucene.codecs.CodecUtil.checksumEntireFile(CodecUtil.java:547)
        at org.apache.lucene.codecs.blocktree.BlockTreeTermsReader.checkIntegrity(BlockTreeTermsReader.java:349)
        at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat$FieldsReader.checkIntegrity(PerFieldPostingsFormat.java:371)
        at org.apache.lucene.codecs.perfield.PerFieldMergeState$FilterFieldsProducer.checkIntegrity(PerFieldMergeState.java:271)
        at org.apache.lucene.codecs.FieldsConsumer.merge(FieldsConsumer.java:96)
        at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat$FieldsWriter.merge(PerFieldPostingsFormat.java:197)
        at org.apache.lucene.index.SegmentMerger.mergeTerms(SegmentMerger.java:244)
        at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:139)
        at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4626)
        at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:4219)
        at org.apache.lucene.index.IndexWriter$IndexWriterMergeSource.merge(IndexWriter.java:5812)
        at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:624)
        at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:682)
[2021-01-21 13:13:31.395] (org.apache.hadoop.hbase.regionserver.SplitLogWorker:169)[INFO] - Sending interrupt to stop the worker thread
[2021-01-21 13:13:31.395] (org.apache.hadoop.hbase.regionserver.HRegionServer:143)[ERROR] - RegionServer abort: loaded coprocessors are: [org.apache.hadoop.hbase.coprocessor.HydrogenRegionCoprocessor, org.apache.hadoop.hbase.coprocessor.MultiRowMutationEndpoint]
[2021-01-21 13:13:31.397] (org.apache.hadoop.hbase.regionserver.HRegionServer:1093)[INFO] - Stopping infoServer
[2021-01-21 13:13:31.397] (org.apache.hadoop.hbase.regionserver.SplitLogWorker:151)[INFO] - SplitLogWorker interrupted. Exiting.
[2021-01-21 13:13:31.398] (org.apache.hadoop.hbase.regionserver.SplitLogWorker:160)[INFO] - SplitLogWorker test2,16021,1611205808185 exiting
[2021-01-21 13:13:31.406] (org.eclipse.jetty.server.handler.ContextHandler:910)[INFO] - Stopped o.e.j.w.WebAppContext@62775fe9{/,null,UNAVAILABLE}{jar:file:/data/logs/hadoop_local_dir/usercache/root/filecache/2307/__spark_libs__3607248004833691317.zip/hbase-server-2.2.5.jar!/hbase-webapps/regionserver}
[2021-01-21 13:13:31.407] (org.apache.hadoop.hbase.regionserver.HRegionServer:2449)[INFO] - Dump of metrics as JSON on abort: {
  "beans": [
    {
      "name": "java.lang:type=Memory",
      "modelerType": "sun.management.MemoryImpl",

**Comment by muyannian** [comment]
if (blockCacheEnabled) {
            int numberOfBlocksPerBank = configuration.getInt(NUMBEROFBLOCKSPERBANK, 16384);
            int blockSize = BlockDirectory.BLOCK_SIZE;
            int bankCount = configuration.getInt(BLOCKCACHE_SLAB_COUNT, 2);
            boolean directAllocation = configuration.getBoolean(BLOCKCACHE_DIRECT_MEMORY_ALLOCATION, true);
            int slabSize = numberOfBlocksPerBank * blockSize;
            LOG.info(
                    "Number of slabs of block cache [{}] with direct memory allocation set to [{}]",
                    bankCount, directAllocation);
            LOG.info(
                    "Block cache target memory usage, slab size of [{}] will allocate [{}] slabs and use ~[{}] bytes",
                    new Object[]{slabSize, bankCount, ((long) bankCount * (long) slabSize)});

            int bsBufferSize = configuration.getInt("index.hdfs.blockcache.bufferstore.buffersize", blockSize);
            int bsBufferCount = configuration.getInt("index.hdfs.blockcache.bufferstore.buffercount", 0); // this is actually total size

            BlockCache blockCache = getBlockDirectoryCache(numberOfBlocksPerBank,
                    blockSize, bankCount, directAllocation, slabSize,
                    bsBufferSize, bsBufferCount, blockCacheGlobal);

            IndexCache indexCache = new BlockDirectoryCache(blockCache, indexDataPath.getName());
            int readBufferSize = configuration.getInt("index.hdfs.blockcache.read.buffersize", blockSize);
            hdfsDir = new HdfsDirectory(indexDataPath,  new SingleInstanceLockFactory(), configuration, readBufferSize);

            Set<String> blockCacheFileTypes = Sets.newHashSet("doc", "tim", "si"  );
            //Set<String> blockCacheFileTypes = Sets.newHashSet();
            this.directory = new BlockDirectory(indexDataPath.getName(),hdfsDir, indexCache, blockCacheFileTypes, blockCacheReadEnabled, true);

        } else {
            this.directory = new HdfsDirectory(indexDataPath, configuration);
        }

**Comment by gleonSun** [comment]
调试后更改了部分参数，同时取消了 cacheReadOnce，支持对稍大一些的文件进行 BlockCache 的读缓存，仅读一次的文件不再加载，测试正常运行。
